### ISSUE TITLE
[Feature] commit signature verification

### ISSUE THREAD

**Issue by shenxianpeng** [commit-check/commit-check#37]
Check commit signatures

**Comment by 2bndy5** [comment]
Does "signature" mean "commit message has a 'Signed off by: \<email>'"  in the trailer(s)? 

I think a very commonly desirable commit check is to make sure a commit message has a "Signed off by: \<email>" trailer. Some projects even require contributions to have a "Signed off by: \<author-email>" in the end of the commit message.
